# Generated by Django 4.0.5 on 2022-06-15 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='users_liked',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
